services:
  app:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image:
      postgres:16
    environment:
      POSTGRES_DB: "java_app_db"
      POSTGRES_USER: "app_user"
      POSTGRES_PASSWORD: "23bjf8Gewb3"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/docker-entrypoint-initdb.d
      - javaapp-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  javaapp-data: