services:
  app:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db

  postgres_db:
    image:
      postgres:16
    environment:
      POSTGRES_DB: "java_app_db"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/docker-entrypoint-initdb.d
      - javaapp-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

volumes:
  javaapp-data: